project_id = "mbirmjqiepvmmjpwzjut"

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.generate-funnel]
verify_jwt = false

[functions.analyze-site]
verify_jwt = false

[functions.generate-email]
verify_jwt = false
